### ISSUE TITLE
some a11y issues

### ISSUE THREAD

**Issue by werdnanoslen** [OpenSourceActivismTech/betterplatform#1]
Hi folks, happy to see this! I have some a11y fixes I'll make a PR for, but just in case y'all are faster or I can't:

- add `aria-hidden=true` to the navigation icons (not the links)
- add alt text to all images
- add `title` and `desc` tags to all SVGs
- add `aria-labelledby` to the “what do you imagine” input, referring to the `<h1>` above it by ID
- improve the color contrast on the “better late than never” section for text, inputs, and buttons. Could probably slightly lighten the yellow and slightly darken the red to get it right
- the country `<select>` is… odd, it appears to just be text, after one click it changes to “united states” (for me, currently in the US), and then clicking it makes it sort of behave as a `<select>`, but it has a `<span>` below it holding the selected value. :thinking_face: I’d change it to just a simple label + select fieldset. This was confusing even as a sighted person.

**Comment by jlev** [comment]
Thanks for the help @werdnanoslen. We don't actually control the markup from ActionNetwork, because it gets rendered by their javascript. We *could* switch to using their API and post signups directly, but that requires a higher level of access than we currently have. So, I think that'll need to stay as it is for the moment. The rest of this looks great!
